### PR TITLE
chore: reduce unnecessary path point precision

### PR DESCRIPTION
**Pull request by nickofthyme**
## Summary

This PR has _virtually_ no visual change on the look of the charts. This change simply reduces the pixel precision to 2 decimals to reduce the `length` of the path strings.

### Example

Take the basic area chart like this...

image

the area `path` would be

```
//before - length = 6900
M0,257.4794895168642L3.941176470588235,261.50865998176846L7.88235294117647,261.97356426618046L11.823529411764707,269.334548769371L15.76470588235294,253.06289881494985L19.705882352941178,225.47857793983593L23.647058823529413,211.2215132178669L27.588235294117645,205.6426618049225L31.52941176470588,207.19234275296262L35.470588235294116,225.3236098450319L39.411764705882355,225.0911577028259L43.35294117647059,240.27803099361896L47.294117647058826,241.59525979945306L51.23529411764706,245.85688240656336L55.17647058823529,242.98997265268915L59.11764705882353,240.35551504102096L63.05882352941176,200.60619872379215L67,234.46672743846855L70.94117647058823,258.25432999088423L74.88235294117646,255.69735642661806L78.82352941176471,268.0173199635369L82.76470588235294,255.54238833181404L86.70588235294117,232.91704649042845L90.64705882352942,229.66271649954422L94.58823529411765,127.69371011850501L98.52941176470588,162.25159525979944L102.47058823529412,75.77939835916135L106.41176470588235,28.66909753874205L110.35294117647058,102.43391066545124L114.29411764705883,181.3126709206928L118.23529411764706,221.2169553327256L122.1764705882353,249.11121239744756L126.11764705882352,260.8500455788514L130.05882352941177,268.947128532361L134,266.66134913400185L137.94117647058823,283.630355515041L141.88235294117646,290.8363719234275L145.8235294117647,297.732452142206L149.76470588235293,229.74020054694623L153.7058823529412,232.3746581586144L157.64705882352942,214.86326344576116L161.58823529411765,229.74020054694623L165.52941176470588,224.31631722880581L169.47058823529412,229.81768459434824L173.41176470588235,234.8541476754786L177.35294117647058,228.73290793072016L181.29411764705884,205.79762989972653L185.23529411764704,186.65907019143117L189.1764705882353,189.44849589790337L193.1176470588235,221.13947128532362L197.05882352941177,93.91066545123061L201,127.07383773928896L204.94117647058823,196.34457611668188L208.8823529411765,241.20783956244304L212.8235294117647,232.3746581586144L216.76470588235296,219.82224247948952L220.70588235294116,147.83956244302644L224.64705882352942,135.59708295350958L228.58823529411765,176.50865998176846L232.52941176470588,186.11668185961713L236.47058823529412,192.08295350957155L240.41176470588232,232.06472196900637L244.3529411764706,243.22242479489518L248.29411764705884,254.45761166818596L252.23529411764704,248.56882406563355L256.17647058823525,255.30993618960804L260.11764705882354,256.6271649954421L264.05882352941177,273.8286235186873L268,268.13354603463995L271.94117647058823,269.567000911577L275.88235294117646,269.64448495897904L279.8235294117647,232.76207839562443L283.7647058823529,231.83226982680037L287.7058823529412,216.49042844120328L291.6470588235294,221.99179580674564L295.5882352941176,232.1422060164084L299.52941176470586,216.8778486782133L303.47058823529414,213.23609845031905L307.4117647058824,0L311.35294117647055,44.01093892433914L315.29411764705884,117.7757520510483L319.2352941176471,180.84776663628077L323.1764705882353,214.70829535095714L327.11764705882354,252.59799453053785L331.05882352941177,271.23290793072016L335,279.2137648131267L338.94117647058823,283.475387420237L342.88235294117646,285.56745670009116L346.8235294117647,220.7520510483136L350.7647058823529,196.34457611668188L354.70588235294116,212.15132178669097L358.6470588235294,225.1686417502279L362.5882352941177,233.30446672743847L366.52941176470586,241.59525979945306L370.4705882352941,235.78395624430266L374.4117647058824,227.18322698268003L378.3529411764706,182.39744758432087L382.29411764705884,199.21148587055606L386.235294117647,224.70373746581583L390.1764705882353,223.6189608021878L394.11764705882354,239.1932543299909L398.05882352941177,247.79398359161348L402,265.0729261622607L405.94117647058823,268.830902461258L409.88235294117646,281.8094804010939L413.8235294117647,272.27894257064725L417.764705882353,235.0865998176846L421.7058823529412,179.9179580674567L425.6470588235294,184.87693710118504L429.5882352941176,209.5943482224248L433.5294117647059,221.83682771194168L437.47058823529414,240.20054694621695L441.4117647058823,264.02689152233364L445.35294117647055,250.6608933454877L449.29411764705884,252.90793072014586L453.2352941176471,260.26891522333636L457.1764705882353,86.93710118505015L461.1176470588235,155.12306289881496L465.05882352941177,209.12944393801277L469,238.88331814038287L469,340L465.05882352941177,340L461.1176470588235,340L457.1764705882353,340L453.2352941176471,340L449.29411764705884,340L445.35294117647055,340L441.4117647058823,340L437.47058823529414,340L433.5294117647059,340L429.5882352941176,340L425.6470588235294,340L421.7058823529412,340L417.764705882353,340L413.8235294117647,340L409.88235294117646,340L405.94117647058823,340L402,340L398.05882352941177,340L394.11764705882354,340L390.1764705882353,340L386.235294117647,340L382.29411764705884,340L378.3529411764706,340L374.4117647058824,340L370.4705882352941,340L366.52941176470586,340L362.5882352941177,340L358.6470588235294,340L354.70588235294116,340L350.7647058823529,340L346.8235294117647,340L342.88235294117646,340L338.94117647058823,340L335,340L331.05882352941177,340L327.11764705882354,340L323.1764705882353,340L319.2352941176471,340L315.29411764705884,340L311.35294117647055,340L307.4117647058824,340L303.47058823529414,340L299.52941176470586,340L295.5882352941176,340L291.6470588235294,340L287.7058823529412,340L283.7647058823529,340L279.8235294117647,340L275.88235294117646,340L271.94117647058823,340L268,340L264.05882352941177,340L260.11764705882354,340L256.17647058823525,340L252.23529411764704,340L248.29411764705884,340L244.3529411764706,340L240.41176470588232,340L236.47058823529412,340L232.52941176470588,340L228.58823529411765,340L224.64705882352942,340L220.70588235294116,340L216.76470588235296,340L212.8235294117647,340L208.8823529411765,340L204.94117647058823,340L201,340L197.05882352941177,340L193.1176470588235,340L189.1764705882353,340L185.23529411764704,340L181.29411764705884,340L177.35294117647058,340L173.41176470588235,340L169.47058823529412,340L165.52941176470588,340L161.58823529411765,340L157.64705882352942,340L153.7058823529412,340L149.76470588235293,340L145.8235294117647,340L141.88235294117646,340L137.94117647058823,340L134,340L130.05882352941177,340L126.11764705882352,340L122.1764705882353,340L118.23529411764706,340L114.29411764705883,340L110.35294117647058,340L106.41176470588235,340L102.47058823529412,340L98.52941176470588,340L94.58823529411765,340L90.64705882352942,340L86.70588235294117,340L82.76470588235294,340L78.82352941176471,340L74.88235294117646,340L70.94117647058823,340L67,340L63.05882352941176,340L59.11764705882353,340L55.17647058823529,340L51.23529411764706,340L47.294117647058826,340L43.35294117647059,340L39.411764705882355,340L35.470588235294116,340L31.52941176470588,340L27.588235294117645,340L23.647058823529413,340L19.705882352941178,340L15.76470588235294,340L11.823529411764707,340L7.88235294117647,340L3.941176470588235,340L0,340Z

// after - length = 2860
M0,257.47L3.94,261.5L7.88,261.97L11.82,269.33L15.76,253.06L19.7,225.47L23.64,211.22L27.58,205.64L31.52,207.19L35.47,225.32L39.41,225.09L43.35,240.27L47.29,241.59L51.23,245.85L55.17,242.98L59.11,240.35L63.05,200.6L67,234.46L70.94,258.25L74.88,255.69L78.82,268.01L82.76,255.54L86.7,232.91L90.64,229.66L94.58,127.69L98.52,162.25L102.47,75.77L106.41,28.66L110.35,102.43L114.29,181.31L118.23,221.21L122.17,249.11L126.11,260.85L130.05,268.94L134,266.66L137.94,283.63L141.88,290.83L145.82,297.73L149.76,229.74L153.7,232.37L157.64,214.86L161.58,229.74L165.52,224.31L169.47,229.81L173.41,234.85L177.35,228.73L181.29,205.79L185.23,186.65L189.17,189.44L193.11,221.13L197.05,93.91L201,127.07L204.94,196.34L208.88,241.2L212.82,232.37L216.76,219.82L220.7,147.83L224.64,135.59L228.58,176.5L232.52,186.11L236.47,192.08L240.41,232.06L244.35,243.22L248.29,254.45L252.23,248.56L256.17,255.3L260.11,256.62L264.05,273.82L268,268.13L271.94,269.56L275.88,269.64L279.82,232.76L283.76,231.83L287.7,216.49L291.64,221.99L295.58,232.14L299.52,216.87L303.47,213.23L307.41,0L311.35,44.01L315.29,117.77L319.23,180.84L323.17,214.7L327.11,252.59L331.05,271.23L335,279.21L338.94,283.47L342.88,285.56L346.82,220.75L350.76,196.34L354.7,212.15L358.64,225.16L362.58,233.3L366.52,241.59L370.47,235.78L374.41,227.18L378.35,182.39L382.29,199.21L386.23,224.7L390.17,223.61L394.11,239.19L398.05,247.79L402,265.07L405.94,268.83L409.88,281.8L413.82,272.27L417.76,235.08L421.7,179.91L425.64,184.87L429.58,209.59L433.52,221.83L437.47,240.2L441.41,264.02L445.35,250.66L449.29,252.9L453.23,260.26L457.17,86.93L461.11,155.12L465.05,209.12L469,238.88L469,340L465.05,340L461.11,340L457.17,340L453.23,340L449.29,340L445.35,340L441.41,340L437.47,340L433.52,340L429.58,340L425.64,340L421.7,340L417.76,340L413.82,340L409.88,340L405.94,340L402,340L398.05,340L394.11,340L390.17,340L386.23,340L382.29,340L378.35,340L374.41,340L370.47,340L366.52,340L362.58,340L358.64,340L354.7,340L350.76,340L346.82,340L342.88,340L338.94,340L335,340L331.05,340L327.11,340L323.17,340L319.23,340L315.29,340L311.35,340L307.41,340L303.47,340L299.52,340L295.58,340L291.64,340L287.7,340L283.76,340L279.82,340L275.88,340L271.94,340L268,340L264.05,340L260.11,340L256.17,340L252.23,340L248.29,340L244.35,340L240.41,340L236.47,340L232.52,340L228.58,340L224.64,340L220.7,340L216.76,340L212.82,340L208.88,340L204.94,340L201,340L197.05,340L193.11,340L189.17,340L185.23,340L181.29,340L177.35,340L173.41,340L169.47,340L165.52,340L161.58,340L157.64,340L153.7,340L149.76,340L145.82,340L141.88,340L137.94,340L134,340L130.05,340L126.11,340L122.17,340L118.23,340L114.29,340L110.35,340L106.41,340L102.47,340L98.52,340L94.58,340L90.64,340L86.7,340L82.76,340L78.82,340L74.88,340L70.94,340L67,340L63.05,340L59.11,340L55.17,340L51.23,340L47.29,340L43.35,340L39.41,340L35.47,340L31.52,340L27.58,340L23.64,340L19.7,340L15.76,340L11.82,340L7.88,340L3.94,340L0,340Z
```

### Checklist

- [ ] Proper documentation or storybook story was added for features that require explanation or tutorials
- [ ] Unit tests were updated or added to match the most common scenarios

### CODE REVIEW

**Comment by monfera** [comment]
I tested such path string truncation in the past on a similar motive (many years ago, so might have changed) and couldn't measure a clear speed difference either way between string truncation and not. Apparently, serialization was pretty quick and it's not data that goes through the network. I'm also not aware of this being a common optimization tip (except for network transfer). If we micro-optimize something like this, and the perf gains are not obvious (eg. in contrast to how you could detect the initial slowness of icicle/flame) it's worth adding results of perf benchmarking, to show the gains. Absolutely interested if it turns out to be an effective perf tweak this time around

**Comment by nickofthyme** [comment]
Yeah I agree, if there's no performance then it's not needed. I could see a benefit if we eventually allow exporting as svg to limit the export file size.

Looks like d3 has also discussed doing this https://github.com/d3/d3-path/issues/10 in the last five years since opening the issue.

**Comment by monfera** [comment]
Yes, it can be handy for serialization, and there, even the two decimals would be way too many. Rounding to whole pixels may be fine. Even on the offchane that the 0.5px error is too much, the viewbox dimensions with SVG can be made eg. double, to gain another doubling of precision while not having to use the noisy decimal dot. Also, if export size becomes a concern, maybe it'll be because it's so dense, every screen pixel has multiple data points, ie. it's better to pre-aggregate before export. Eg. for geo shapes, [TopoJSON](https://github.com/topojson/topojson) and [SVGO](https://jakearchibald.github.io/svgomg/) has a bunch of other tricks up its sleeve that we could then use.

**Comment by monfera** [comment]
... some other techniques for SVG compression, if ever needed - besides rounding - include the use of `<marker>`s for repeated, identically looking things such as axis ticks, [points](https://codepen.io/monfera/pen/rLYqWR) and even [bars](https://codepen.io/monfera/pen/xXmpbY)—though we probably won't need to get sophisticated with typical data

**Comment by nickofthyme** [comment]
Closing for now, can revisit later.

**Pull request closed without merging**
