### PR TITLE
fix: overwritting of axis by gridlines 

### LINKED ISSUE #1203: The gridline hides the horizontal axis
**Describe the bug**
Axis are rendered before rendering the grids.
This causes a rendering problem: the X-axis will be every time overwritten by the lowest horizontal grid line style that is always rendered on top of the axis line.

**To Reproduce**
1. Go to https://codesandbox.io/s/kind-fermat-hx7us?file=/src/App.tsx
2. The gridline is enabled, the axis line stroke color is set to black but the gridline covers the axis line

**Expected behavior**
The gridlines should be rendered before rendering the axis so that the axis is more prominent and can be styled correctly.

**Additional context**
A similar effect is also visible on the Y-axis where the horizontal grid lines are rendered on top, creating a dashed effect on the Y-axis line

**Screenshots**
Screenshot 2021-06-14 at 11 19 27

**Additional context**
A VRT should be added

### PR DESCRIPTION
**Pull request by ron-debajyoti**
## Summary
Fixes #1203 by rendering gridlines before axes to prevent overwriting of axes.

### CODE REVIEW

**Comment by markov00** [comment]
jenkins test this please

**Comment by nickofthyme** [comment]
Jenkins test this please

**Comment by ron-debajyoti** [comment]
Hey @markov00 @nickofthyme ,
Based on the jenkins tests, looks like those cases are failing where the previous version of the grid lines are present. Same errors are seen on performing the integration tests.
Suggestions ?

**Comment by markov00** [comment]
> Hey @markov00 @nickofthyme ,
> Based on the jenkins tests, looks like those cases are failing where the previous version of the grid lines are present. Same errors are seen on performing the integration tests.
> Any suggestions ?

Hey @ron-debajyoti I've seen the VRTs changes, you should update the screenshot baseline as we did last time, if you are not sure how to operate we can push these changes for you

**Comment by ron-debajyoti** [comment]
> > Hey @markov00 @nickofthyme ,
> > Based on the jenkins tests, looks like those cases are failing where the previous version of the grid lines are present. Same errors are seen on performing the integration tests.
> > Any suggestions ?
> 
> you should update the screenshot baseline as we did last time, if you are not sure how to operate we can push these changes for you
I would like to continue and learn if you could guide me a bit. So basically I need to update the image snapshots of all those failing test cases right?

**Comment by markov00** [comment]
Awesome, thank you!
So the easiest and only way to update the VRTs is to follow the guide here: https://github.com/elastic/elastic-charts/blob/master/wiki/testing.md#visual-regression-testing

The VRTs suite basically compiles all the storybook examples into a single small application, running on a server. The app is then accessed via Puppeteer on a headless chromium instance that screenshots and compares all the various tests.
As you will read on the guide, if you run without the `-u` option it will create a diff folder with the differences between the baseline screenshots and your version.
Run then the same command with the `-u` to update all the screenshot at once
The process can take quite some time (~10 to 15 minutes) depending if this is the first time you use the VRT server or not

**Comment by ron-debajyoti** [comment]
> Awesome, thank you!
> So the easiest and only way to update the VRTs is to follow the guide here: https://github.com/elastic/elastic-charts/blob/master/wiki/testing.md#visual-regression-testing

Thank you @markov00 . Sorry for missing out on the testing part. 
I added the latest snapshots so perhaps we should jenkins retest this.

**Comment by markov00** [comment]
jenkins test this please

**Comment by ron-debajyoti** [comment]
Tests passed !

**Review by markov00 — APPROVED** [review]
LGTM! Thanks for the changes

**Review by nickofthyme — APPROVED** [review]
Changes look good!

**Pull request merged**
