### PR TITLE
chore(wordcloud): remove tooltip

### LINKED ISSUE #1083: [Wordcloud] follow-up steps
**Is your feature request related to a problem? Please describe.**
The following PR comments by @markov00: #1038

- [x] rename `weightFun` with `weightFn`
- [x] remove `Logger.warn` from default no-room callback
- [x] remove the canvas element completely
- [ ] disable tooltip

### PR DESCRIPTION
**Pull request by Kati-dev-hu**
## Summary

Closes #1083

### CODE REVIEW

**Comment by Kati-dev-hu** [comment]
jenkins please test this

**Comment by monfera** [comment]
jenkins please test this

**Review by markov00 — COMMENTED** [review]
Awesome, thanks for that.
I think we should disable (returning empty/false values) to the following methods:
`isTooltipVisible` and `getTooltipInfo` on the `chart_state.tsx`

**Comment by monfera** [comment]
jenkins please test this

**Review by markov00 — APPROVED** [review]
Great thanks again Kati really appreciated it!

**Pull request merged**
