### PR TITLE
docs: update bug template

### PR DESCRIPTION
**Pull request by markov00**
## Summary
A slight adjustment to the bug template

### CODE REVIEW

**Review by nickofthyme — APPROVED** [review]
It would be cool to use GitHub's new issue configuration eventually. I think it is not yet fully supported or featured though.

https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms

**Comment by markov00** [comment]
> It would be cool to use GitHub's new issue configuration eventually. I think it is not yet fully supported or featured though.
> 
> https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository#creating-issue-forms

Oh nice, that's even better, let me try

**Comment by markov00** [comment]
It actually doesn't show you the preview, so it's completely a blind edit 😬

**Comment by markov00** [comment]
I've created this form to test: https://github.com/markov00/test-gh-form/issues/new?assignees=&labels=bug&template=bug_report.yaml
What do you think @nickofthyme ?

**Comment by nickofthyme** [comment]
> I've created this form to test: https://github.com/markov00/test-gh-form/issues/new?assignees=&labels=bug&template=bug_report.yaml What do you think @nickofthyme ?

Looks good to me. That's strange that they preview it in markdown.

**Comment by markov00** [comment]
> > I've created this form to test: https://github.com/markov00/test-gh-form/issues/new?assignees=&labels=bug&template=bug_report.yaml What do you think @nickofthyme ?
> 
> Looks good to me. That's strange that they preview it in markdown.

I know.
Actually it also looks a very long set of fields, where most of them are skippable. We can probably wait until that will be out of beta

**Pull request merged**
