### PR TITLE
docs: improve metric story

### PR DESCRIPTION
**Pull request by drewdaemon**
## Summary

- replaces "layout" setting with "number of columns" to match Lens
- resizes container based on grid size
- changes each metric to be `200px x 200px` to match Lens
- fixes max trend data points
- fixes progress bar direction
- fixes progress bar toggle

https://github.com/elastic/elastic-charts/assets/315764/293904c6-55cc-4326-a24a-f524f6f1d44f

### Checklist

- [x] The proper **chart type** label has been added (e.g. `:xy`, `:partition`)
- [x] The proper **feature** labels have been added (e.g. `:interactions`, `:axis`)
- [x] The proper documentation and/or storybook story has been added or updated
- [ ] The code has been checked for cross-browser compatibility (Chrome, Firefox, Safari, Edge)

### CODE REVIEW

**Comment by drewdaemon** [comment]
@nickofthyme I changed the size of the metrics in the story. How do I go about updating the baselines?

**Comment by nickofthyme** [comment]
@drewdaemon you just need to leave a comment `buildkite update screenshots` and buildkite will run the tests in update mode.

**Comment by nickofthyme** [comment]
buildkite update screenshots

**Comment by nickofthyme** [comment]
@drewdaemon It's clipping the bottom because the playwright browser viewport size it too small. I'll take a look at this in the morning.

image

**Comment by nickofthyme** [comment]
FYI I'm testing a fix over here -> https://github.com/elastic/elastic-charts/pull/2239

**Comment by nickofthyme** [comment]
buildkite update screenshots

**Comment by nickofthyme** [comment]
buildkite update screenshots

**Review by nickofthyme — APPROVED** [review]
Changes LGTM, sorry about the vrt issues 😅

**Comment by drewdaemon** [comment]
Thanks @nickofthyme !

**Pull request merged**
