### PR TITLE
ci: remove obsolete configurations

### PR DESCRIPTION
**Pull request by nickofthyme**
## Summary

Remove obsolete configurations after `buildkite` migration.

## Details

Changes include:
- Removes `.ci/` with jenkins configs
- Removes `.github/` actions and workflow. Excludes only `release.yml` to be migrated to buildkite.
- Removes `integration/`
- Corrects all usages of `integration/` throughout the code and change to new `e2e` usage.
- Updates `testing.md` to reflect latest VRT usages

## Issues

#1617

### CODE REVIEW

**Comment by nickofthyme** [comment]
buildkite update vrt

**Review by markov00 — COMMENTED** [review]
Can you remove also every dependencies on puppeteer we have?
like:
```
"jest-puppeteer": "6.1.1",
"jest-puppeteer-docker": "^1.4.2",
 "puppeteer": "^5.5.0",
"@types/expect-puppeteer": "^4.4.5",
"@types/jest-environment-puppeteer": "^5.0.2",
 "@types/puppeteer": "^5.4.2",

```

And probably anything related to `jest-image-snapshot`

**Comment by nickofthyme** [comment]
buildkite test this

**Review by markov00 — APPROVED** [review]
LGTM, thanks for this big cleanup!

**Pull request merged**
