### PR TITLE
docs: add favicon and brandImage

### PR DESCRIPTION
**Pull request by markov00**
## Summary

I've moved the storybook icon to be picked up as a favicon instead of including it into the `head` tag.
This just prevents Storybook from loading the logo on every page.

I've also changed the brandImage to use our logo
Screenshot 2021-02-10 at 11 11 03

### CODE REVIEW

**Review by nickofthyme — APPROVED** [review]
🎉

**Review by rshen91 — APPROVED** [review]
Nice!

**Review by miukimiu — APPROVED** [review]
LGTM! 🥳 🎉

**Pull request merged**
