### PR TITLE
fix: add clip paths to highlighter component

### PR DESCRIPTION
**Pull request by markov00**
## Summary

The highlighter component doesn't properly handle custom Y domains, displaying the highlighted element outside the chart.

This PR fix it adding a clip area.

**Before**:
Screenshot 2019-10-31 at 17 42 39

**After**:
Screenshot 2019-10-31 at 17 43 04

### Checklist

Use ~~strikethroughs~~ to remove checklist items you don't feel are applicable to this PR.

- ~[ ] Any consumer-facing exports were added to `src/index.ts` (and stories only import from `../src` except for test data & storybook)~
- [x] This was checked for cross-browser compatibility, [including a check against IE11](https://github.com/elastic/kibana/blob/master/CONTRIBUTING.md#cross-browser-compatibility)
- ~[ ] Proper documentation or storybook story was added for features that require explanation or tutorials~
- ~[ ] Unit tests were updated or added to match the most common scenarios~
- [x] Each commit follows the [convention](https://github.com/elastic/elastic-charts/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by nickofthyme** [comment]
It looks like this causes a small regression with the clipping changes you made a few months ago related to the point on the end.

Looks like it is only clipping the hovered point styles and not the points themselves.

## Current
image


## Your changes

image

**Comment by markov00** [comment]
> It looks like this causes a small regression with the clipping changes you made a few months ago related to the point on the end.
> 
> Looks like it is only clipping the hovered point styles and not the points themselves.
> 
> ## Current
> image
> 
> ## Your changes
> image

@nickofthyme fixed in 27f6ad2

**Pull request merged**
