### PR TITLE
ci: add license scan and split jobs

### PR DESCRIPTION
**Pull request by markov00**
## Summary

This PR adds the FOSSA license scan and split our single job into multiple jobs:
- eslint check and typecheck
- unit tests
- visual regression tests
- license scan

It use a `multijob` project type as done in EUI https://github.com/elastic/eui/tree/master/.ci/jobs

Right now the license scan only output the result on the stdout, we will update in a subsequent PR to:
runs the license scan only if we have changes on the `package.json` file and push it to FOSSA app

### CODE REVIEW

**Comment by nickofthyme** [comment]
Nice!! You'll have to walk us through the changes when your ready for review. 🍾

**Comment by markov00** [comment]
@jonahbull I've tried to run this locally but it took me days to make Jenkins works locally without success. I managed to make it work and run few times, but for example the main job: `elastic+elastic-charts+pull-request` is not seen as multijob on Jenkins, but I just see our jobs as separate jobs. I've tried to specify only `elastic+elastic-charts+pull-request` on the `make jjbb` command but it didn't work (no jobs are picked up, only using `*`)
Is there anything that I can do to test it on our CI from this PR?

**Comment by jonahbull** [comment]
@markov00 I pulled these changes down locally and did the standard `make start` and `make jjbb` steps, selecting all (`*`) jobs. `elastic+elastic-charts+pull-request` is seen as a multijob, though you can't tell from the main Jenkins view.

Screen Shot 2020-06-29 at 7 05 11 PM

**Pull request merged**
