### PR TITLE
refactor: rename enum types to singular

### PR DESCRIPTION
**Pull request by wayneseymour**
Simple search and replace...low hanging fruit.
Also, not sure if the markdown files should be included in this refactor?

fix https://github.com/elastic/elastic-charts/issues/767
## Summary

I was searching for an easy pr to start understanding this repo.

I think there are still more enums to fixup, such as:
https://github.com/elastic/elastic-charts/blob/dce139a1e72b2ad136cb09dc4c705dcfff1720e6/src/specs/constants.ts#L27

### CODE REVIEW

**Comment by monfera** [comment]
Thanks @wayneseymour for your PR! 

- The `api/charts.api.md` file can be regenerated with `yarn build:ts && yarn api:extract` and the output file (that gets output a different location) can be copied in place of `api/charts.api.md` and checked eg. via diffing if the changes are as you expect
- The PR itself looks good to me, wondering @markov00 what our policy is for approving/merging PRs that break the API without a linked requirement by the dependency, Kibana—I guess it's best to batch such changes to minimize disruption. But batching means, longer wait till it hits `master`, with inevitable merge conflicts, as a maintenance PR impacts many lines. Future additions of `ChartTypes` also won't be covered (TS checks should catch this). Ie. there's more work than usual on the part of the PR maker and whoever works on future merges.

Tre' one note is that sometimes we're assisting Kibana users in such API changes, eg. via small PRs there by the chart PR maker 😉 That's also a reason for, I think, merging a bunch of API breaking changes in one fell swoop, Marco what do you think, with 7.12 around the corner?

**Comment by markov00** [comment]
Thank you Tre'!
This should definitely include the `BREAKING CHANGE` footer
We can merge this and update 7.13 branch, it will not be merged on 7.12 as we can't introduce breaking changes after FF

I think it's fine to include multiple changes here, some enums are not currently used much outside the library

**Comment by nickofthyme** [comment]
Thanks @wayneseymour this issue is very near and dear to my ❤️ 

@monfera I think this is just a nice to have that will eventually get into `7.13` so I don't think we need to be too critical of batching other PRs nor waiting to get others merged before this as we could just backport any critical changes to `7.12` in the few remaining days. Also we end up having to merge the PRs so one of us should be sure to note the `BREAKING CHANGE`.

**Comment by wayneseymour** [comment]
> Thanks @wayneseymour for your PR!
> 
> * The `api/charts.api.md` file can be regenerated with `yarn build:ts && yarn api:extract` and the output file (that gets output a different location) can be`cp tmp/charts.api.md api/charts.api.md`-ed in place of `api/charts.api.md` and checked eg. via diffing if the changes are as you expect
> * The source change looks good, wondering @markov00 what our policy is for approving/merging PRs that break the API without a linked requirement by the dependency, Kibana—I guess it's best to batch such changes to minimize the # of BREAKING. But batching means, longer wait till it hits `master`, with inevitable merge conflicts, as a maintenance PR impacts many lines. Future additions of `ChartTypes` also won't be covered (TS checks should catch this). Ie. there's more work than usual on the part of the PR maker and whoever works on future merges
> * It's good to run tests locally too, including, in such cases when many files are changed, the image tests, glad to help setting it up; besides firing up storybook and testing a variety of charts manually
> * Tre' a note for merge time, `elastic-charts` has commit message content conventions for breaking changes, see [here](https://github.com/elastic/elastic-charts/blob/master/CONTRIBUTING.md?rgh-link-date=2021-03-10T12%3A49%3A44Z#squash-and-merge-your-pr)
> 
> Tre' one note is that sometimes we're assisting Kibana users in such API changes, eg. via small PRs there by the chart PR maker 😉 That's also a reason for, I think, merging a bunch of API breaking changes in one fell swoop, Marco what do you think, with 7.12 around the corner?

Awesome, I'll get on this next week!  "Shut it down day" tomorrow in the US :)

**Comment by wayneseymour** [comment]
> Thank you Tre'!
> This should definitely include the `BREAKING CHANGE` footer
> We can merge this and update 7.13 branch, it will not be merged on 7.12 as we can't introduce breaking changes after FF
> 
> I think it's fine to include multiple changes here, some enums are not currently used much outside the library

Perfect, I'll fixup asap!  Thanks for reviewing!

**Comment by wayneseymour** [comment]
@monfera @nickofthyme Gents, I'm not sure how to proceed here.
The issue is with symbol shadowing.  In this case, the `object` and the `type` would have the same name if I refactored away the plurality.
Ideas?


Screen Shot 2021-03-26 at 1 19 55 PM

**Comment by monfera** [comment]
@wayneseymour that's fine, please see eg. `LegendStrategy` or other similar symbols that get dual-bound (one value, one type) as part of our current approach of working around (or rather, avoid) TypeScript enums
```
export type LegendStrategy = Values<typeof LegendStrategy>;
```

**Comment by wayneseymour** [comment]
Locally, I've run these build scripts and they passed:
 - `yarn build:ts && yarn api:extract`
 - `yarn lint:fix`
 - `yarn test`

**Review by markov00 — APPROVED** [review]
LGTM, scanned all the changes online and looks great!
Thanks for taking the time for that.
Just remember to add a breaking change line in the merge commit like the following:
```
your PR description

BREAKING CHANGE: `AnnotationDomainTypes`, `AnnotationType` and all the others (please list them) are renamed to ....
```

**Comment by wayneseymour** [comment]
> LGTM, scanned all the changes online and looks great!
> Thanks for taking the time for that.
> Just remember to add a breaking change line in the merge commit like the following:
> 
> ```
> your PR description
> 
> BREAKING CHANGE: `AnnotationDomainTypes`, `AnnotationType` and all the others (please list them) are renamed to ....
> ```

Indeed I will!  Thanks @markov00

**Comment by nickofthyme** [comment]
> Gents, I'm not sure how to proceed here.
The issue is with symbol shadowing. In this case, the object and the type would have the same name if I refactored away the plurality.
Ideas?

Hey @wayneseymour I was sick last week so I didn't see this till now and wanted to clear this up in case you ran into this in the future. I'm thinking this might be an issue with the linter because in typescript when exporting a type or value you create a separate entity for each, so the naming will _not_ clash when doing something like...

```ts
export const SeriesType = Object.freeze({
  Area: 'area' as const,
  Bar: 'bar' as const,
  Line: 'line' as const,
  Bubble: 'bubble' as const,
});
export type SeriesType = $Values<typeof SeriesType>;
```

Typescript calls this [`Declaration Merging`](https://www.typescriptlang.org/docs/handbook/declaration-merging.html) whereby the type and value (and namespaces) are merged into one as `SeriesType` wherever it is imported. In this case, we call this a `const enum` as it is not a typescript `enum`, see https://github.com/elastic/kibana/pull/62957#discussion_r406385788 for a deeper explanation of why.

**Pull request merged**
