### PR TITLE
build: upgade node to 14

### PR DESCRIPTION
**Pull request by markov00**
## Summary

Upgrading node to latest LTS one (also used by Kibana)

I've removed the `engines` requirement from the `package.json` because that engine is only required for the developer environment and not when using the library as a dependency on another app.

Please update your local version of `node` with
```
nvm install 14.15.4
// to make it the default one
nvm alias default 14

```

### CODE REVIEW

**Review by rshen91 — APPROVED** [review]
LGTM thanks!

**Review by nickofthyme — APPROVED** [review]

**Comment by nickofthyme** [comment]
Looks like you need to update the `.ci/global_setup.sh` file

**Comment by markov00** [comment]
jenkins test this

**Pull request merged**
