### PR TITLE
test: fix flaky test with multi-chart interaction tooltip

### PR DESCRIPTION
**Pull request by markov00**
This hopes to fix the flaky test that appears when testing the pointer position across multiple charts.
I've added a delay of 1s for both tests. There was already another test with the same delay so I've just aligned the others.

image

We could reduce this delay if we want, but we just have 3 screenshot with that delay so it doesn't influence much the testing

### CODE REVIEW

**Comment by markov00** [comment]
I need also to unskip one of the test

**Review by monfera — APPROVED** [review]
LGTM, passed on first run 🎉

**Comment by markov00** [comment]
jenkins test this

**Review by nickofthyme — APPROVED** [review]
LGTM, We should revisit this delay when we switch to playwright.

Side note -- I thought this was already added but must have been the one below. Let's see if it behaves.

**Comment by markov00** [comment]
jenkins test this

**Pull request merged**
