### PR TITLE
fix: build issues and tooltip formatting issues

### PR DESCRIPTION
**Pull request by nickofthyme**
## Summary

Fix x-axis and tooltip header formatting caused by #802, by adding `formattedValue` string to `TooltipValue` in addition to actual `value`.

The issue in #802 changed value from the given value to the formatted string value when using the `tooltip.headerFormatter` prop.

Also fixes...
- add `--no-version-updates` flag to storybook start script
- upgrade `@storybook/` dependencies
- remove `@types/react` causing type error in dist library check
- move redux `optionalDependencies` to `devDependencies`

### Checklist

- [x] Any consumer-facing exports were added to `src/index.ts` (and stories only import from `../src` except for test data & storybook)
- [x] Proper documentation or storybook story was added for features that require explanation or tutorials
- [x] Unit tests were updated or added to match the most common scenarios

### CODE REVIEW

**Comment by nickofthyme** [comment]
jenkins retest this please

**Review by monfera — APPROVED** [review]
LGTM on an less than full length look. Would be good to have a visual regression test that passes with this change but wouldn't have passed before this, but it can be added subsequently to merging this PR

**Comment by monfera** [comment]
jenkins retest this please

**Comment by nickofthyme** [comment]
> Would be good to have a visual regression test that passes with this change but wouldn't have passed before this, but it can be added subsequently to merging this PR

Added in bebb62c

**Pull request merged**
