### PR TITLE
fix: update EUI and add autoprefixer

### LINKED ISSUE #249: Elastic-charts on non-white backgrounds
**Is your feature request related to a problem? Please describe.**
Currently elastic-charts renders under the assumption of having a full white (`#fff`) background. If this isn't the case, there are some minor UI issues:
Screenshot 2019-06-25 at 17 14 32

**Describe the solution you'd like**
* No fading background on legend container (or having this behavior configurable)
* Small margin on `.echContainer` (This could also be done on the consumer side, but it's probably a nice default)

**Describe alternatives you've considered**
Having a full white background, which works in this specific case, but it would be nice to even out these cases.

**Checklist**

- [x] this request is checked against already exist requests
- [x] every related Kibana issue is listed under `Kibana Cross Issues` list
- [x] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

### PR DESCRIPTION
**Pull request by markov00**
## Summary

This PR updates EUI to the latest version 12.3.1 fixing the legend shadow problem described in https://github.com/elastic/elastic-charts/issues/249

**before**
Screenshot 2019-07-17 at 15 13 12

**after**
Screenshot 2019-07-17 at 15 10 52

**Test**
Change the `playground` background color of `#root` to a different color than white on the `index.html` file. Add a set of lines series to have a scrolling legend to notice the effect:
```
{
  new Array(60).fill(0).map((d,i) => <LineSeries
    id={getSpecId('dataset ' + i)}
    key={i}
    xScaleType={ScaleType.Time}
    yScaleType={ScaleType.Linear}
    data={KIBANA_METRICS.metrics.kibana_os_load[1].data.slice(0, 15)}
    xAccessor={0}
    yAccessors={[1]}
    stackAccessors={[0]}
  />)
}
```

**Minor issue unsolved**:
The PR add the missing `autoprefixer` plugin for postcss to enable prefixing css styles like `mask-image`. It works correctly on the `playground` and on built bundle (I've checked the compiled css code and seems that all the required styles are correctly prefixed). The missing task is to add the autoprefixer on storybook: @nickofthyme @emmacunningham or @chandlerprall do you have any idea on what I'm doing wrong here?

fix #249

### Checklist

Use ~~strikethroughs~~ to remove checklist items you don't feel are applicable to this PR.

- ~[ ] Any consumer-facing exports were added to `src/index.ts` (and stories only import from `../src` except for test data & storybook)~
- [x] This was checked for cross-browser compatibility, [including a check against IE11](https://github.com/elastic/kibana/blob/master/CONTRIBUTING.md#cross-browser-compatibility)
**note**: `mask-image` used on the legend shadow is not available in IE11. it gracefully fallback to a legend without that shadow 
- ~[ ] Proper documentation or storybook story was added for features that require explanation or tutorials~
- ~[ ] Unit tests were updated or added to match the most common scenarios~
- [x] Each commit follows the [convention](https://github.com/elastic/elastic-charts/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by nickofthyme** [comment]
It looks to me like the autoprefixer is working in storybook. 🤔 

I changed `.storybook/styles.scss` to...

```diff
#root {
  background-color: blanchedalmond;
+  transition: transform 1s;
}
```

and the `.out` bundle output with the plugin was...

```css
#root {
  background-color: blanchedalmond;
  -webkit-transition: -webkit-transform 1s;
  transition: -webkit-transform 1s;
  transition: transform 1s;
  transition: transform 1s, -webkit-transform 1s;
}
```

and without the plugin the output is...

```css
#root {
  background-color: blanchedalmond;
  transition: transform 1s;
}
```

Is there something specific that you noticed that it isn't working?

**Comment by markov00** [comment]
@nickofthyme so if you open storybook and look a chart with a legend, inspect the legend and find the `.echLegendListContainer` class. You will see that the `mask-image` style is not autoprefixed with `-webkit`. On the playground instead if works correctly

**Comment by nickofthyme** [comment]
See https://github.com/markov00/elastic-charts/pull/3

**Pull request merged**
