### PR TITLE
chore: adding pretty-quick commit hook

### PR DESCRIPTION
**Pull request by monfera**
## Summary

Added a [pretty-quick commit hook](https://prettier.io/docs/en/precommit.html#option-2-pretty-quick-https-githubcom-azz-pretty-quick) otherwise the linter will balk on noncompliant code. This'll format all code `prettier`. While we may think of manually formatting a file we're editing, some refactoring steps might touch other files, or one may forget about formatting 10 concurrent files open. I don't see a downside as noncompliant formatting is currently blocking commits. 

### Checklist

Use ~~strikethroughs~~ to remove checklist items you don't feel are applicable to this PR.

- [ ] ~~Any consumer-facing exports were added to `src/index.ts` (and stories only import from `../src` except for test data & storybook)~~
- [ ] ~~This was checked for cross-browser compatibility, [including a check against IE11](https://github.com/elastic/kibana/blob/master/CONTRIBUTING.md#cross-browser-compatibility)~~
- [ ] ~~Proper documentation or storybook story was added for features that require explanation or tutorials~~
- [ ] ~~Unit tests were updated or added to match the most common scenarios~~
- [x] Each commit follows the [convention](https://github.com/elastic/elastic-charts/blob/master/CONTRIBUTING.md)

### CODE REVIEW

**Comment by markov00** [comment]
What if we add also `lint-staged` to check eslint only on staged files?

**Comment by nickofthyme** [comment]
@markov00 I added this to the ci scripts to enforce `yarn.lock` and pull npm modules only from the lock file.

https://github.com/elastic/elastic-charts/blob/59c39bdf21127f797f74a842f3b50bc6905adb99/.ci/run.sh#L96-L100

But it looks like the codcov install runs the install

```bash
18:16:21  -- installing codecov dependencies
18:16:21 yarn add v1.19.1
18:16:21 [1/5] Validating package.json...
18:16:21 [2/5] Resolving packages...
18:16:42 [3/5] Fetching packages...
18:17:02 info fsevents@1.2.9: The platform "linux" is incompatible with this module.
18:17:02 info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
18:17:02 [4/5] Linking dependencies...
18:17:02 warning " > @elastic/eui@13.1.0" has unmet peer dependency "@elastic/datemath@^5.0.2".
18:17:02 warning " > @elastic/eui@13.1.0" has unmet peer dependency "moment@^2.13.0".
18:17:02 warning "semantic-release > marked-terminal@3.2.0" has incorrect peer dependency "marked@^0.4.0 || ^0.5.0 || ^0.6.0".
18:17:35 [5/5] Building fresh packages...
18:17:46 success Saved lockfile. #                           <---- writes lock file????
18:17:46 success Saved 10 new dependencies.
18:17:46 info Direct dependencies
18:17:46 ├─ codecov@3.6.1
18:17:46 └─ pretty-quick@2.0.0
18:17:46 info All dependencies
18:17:46 ├─ argv@0.0.2
18:17:46 ├─ array-differ@3.0.0
18:17:46 ├─ codecov@3.6.1
18:17:46 ├─ mri@1.1.4
18:17:46 ├─ multimatch@4.0.0
18:17:46 ├─ onetime@5.1.0
18:17:46 ├─ pretty-quick@2.0.0
18:17:46 ├─ strip-final-newline@2.0.0
18:17:46 ├─ teeny-request@3.11.3
18:17:46 └─ urlgrey@0.4.4
18:17:46 Done in 85.02s.
18:17:46  -- installing dependencies
18:17:46 yarn install v1.19.1
18:17:47 [1/5] Validating package.json...
18:17:47 [2/5] Resolving packages...
18:17:47 success Already up-to-date. #                           <---- Does nothing
18:17:47 Done in 1.01s.
```

This PR might fix that => https://github.com/elastic/elastic-charts/pull/431/files

**Comment by markov00** [comment]
@nickofthyme I've added a small comment on your PR

**Pull request merged**
