### PR TITLE
fix(flame): undo the conversion to uniform buffer objects

### PR DESCRIPTION
**Pull request by monfera**
## Summary

PR #1690 (`main` commit 67052711) introduced, among numerous other improvements, a conversion to the WebGL2-only uniform buffer objects. Its purpose was mere preparation for eventual WebGPU conversion, which doesn't have singular uniforms, only UBOs. However, certain hardware, OS and browser combinations (specifically, some older Intel MBPs with Chrome and Safari) were flaky with UBOs. As it represented additional code anyway, this PR removes it.

This PR also includes commits with minor WebGL code cleanup and start of documentation. 

## Details

Easiest to review commit by commit

### Checklist

- [x] The proper **chart type** label has been added (e.g. `:xy`, `:partition`)
- [x] The proper **feature** labels have been added (e.g. `:interactions`, `:axis`)
- [x] The code has been checked for cross-browser compatibility (Chrome, Firefox, Safari, Edge)

### CODE REVIEW

**Comment by monfera** [comment]
buildkite test this

**Comment by monfera** [comment]
buildkite update vrt

**Comment by nickofthyme** [comment]
buildkite test this

**Comment by monfera** [comment]
buildkite update vrt

**Comment by markov00** [comment]
buildkite test this

**Review by markov00 — APPROVED** [review]
Changes look ok to me.
Have you found a chrome/safari/webgl issue around that UBO flakyness? If so can you please link it to the PR?

**Comment by monfera** [comment]
@markov00 Safari is good. I haven't found this issue reported in the Chromium bug tracker, it may still exist but it's not an exact science to find earlier reports. Paring down our chart for minimal reproduction would take at least a day. It involves "dumbing down" the WebGL part of the chart to the minimum (eg. minimal shader code, minimal use of kingly) then moving all parts into a single file, and converting it back to JS.

It may not be a browser issue, perhaps Chrome and FF just use different APIs (ANGLE vs Metal) and as such they exercise the specific AMD Radeon MBP driver differently, and all bets are off for fixing rare MBP/Intel/Radeon bugs

 At this point I feel the most efficient thing is to ignore the UBOs for WebGL2. A future WebGPU rewrite will obsolete the issue. But even the broad support of WebGPU may be a year or more away, and there's no known perf benefit for it for the current flamegraph, so may not be worth converting it even then.

All in all, hard to justify spending time on this, imo

**Comment by nickofthyme** [comment]
Released on [`v48.0.1`](https://github.com/elastic/elastic-charts/releases/tag/v48.0.1) upgrading kibana in https://github.com/elastic/kibana/pull/140342

**Pull request merged**
