### PR TITLE
feat(partition): order slices and sectors

### PR DESCRIPTION
**Pull request by monfera**
## Summary

Adds slice sorting for the use of pie charts and sunburst, which allows 
- placing a supplied "Other" slice to be placed at the end, even if, as in this example, the "Other" slice is larger than a regular slice
- slice sorting eg. when the partitioning is along an ordinal variable
- can be used for alphabetical sorting too, though it's almost always a practice to avoid

Closes https://github.com/elastic/elastic-charts/issues/1012
Contributes toward https://github.com/elastic/kibana/issues/90179
Partially addresses https://github.com/elastic/elastic-charts/issues/381

image

The newly introduced `sortPredicate` is for a sort predicate that compares order of any given two `ArrayEntry` objects. `ArrayEntry` has already been part of the public API, so we don't need to publish a new data type for this.

### Checklist

Delete any items that are not applicable to this PR.

- [X] Any consumer-facing exports were added to `src/index.ts` (and stories only import from `../src` except for test data & storybook)
- [X] This was checked for cross-browser compatibility
- [X] Proper documentation or storybook story was added for features that require explanation or tutorials
- [X] Unit tests were updated or added to match the most common scenarios

### CODE REVIEW

**Comment by monfera** [comment]
jenkins please test this

**Comment by stratoula** [comment]
@monfera it seems fine to me. What I want is:
- sort by the metric (numeric). I think that I can do it by just changing the `clockWise`option. 
- sort alphabetically if the user requests it (will use the new sortPredicate for that)

@flash1293 I think it is fine for Lens too. wdyt?

**Comment by monfera** [comment]
@stratoula correct, and if you need special sorting, eg. you want to put the "Other" slice to the end, even if it's not the smallest slice, then you can rely on the `sortPredicate` too

**Review by markov00 — APPROVED** [review]
Tested locally with configurations of `specialFirstInnermostSector` , `clockwiseSectors` and legend. Works as expected

**Comment by flash1293** [comment]
Didn't test the code, but the API looks good to me - a function will give full flexibility which can be use to look up the row index the data table for "user defined" sorting

**Comment by monfera** [comment]
Thanks @markov00 for the review and for @stratoula and @flash1293 for looking at the API. I ended up merging relatively fast as this doesn't lock us in anyway, if there's post-merge or integration time feedback to act upon, and it clears the baseline for the upcoming partition related PRs (lower risk of merge conflict)

**Pull request merged**
