### PR TITLE
ci(renovate): update renovate bot frequency

### PR DESCRIPTION
**Pull request by nickofthyme**
## Summary

Increases renovate bot cadence from 3 to 4 weeks.

### CODE REVIEW

**Review by markov00 — COMMENTED** [review]
Are you sure? I was also considering increasing it a bit more.
If not at least we can start including also other kind of updates, like semantic-release e other general libraries we are using

**Comment by nickofthyme** [comment]
Yeah I'm fine with more, what about every 2 months? It was just getting a bit much all for mostly one or two patch updates.

**Comment by markov00** [comment]
@nickofthyme are you ok reducing this to a bi-weekly frequency?

**Comment by nickofthyme** [comment]
Yeah every 2 weeks is fine for me.

**Review by markov00 — APPROVED** [review]

**Pull request merged**
