### PR TITLE
chore: allow react 18 as peer dependency

### PR DESCRIPTION
**Pull request by nickofthyme**
## Summary

Updates `react` and `react-dom` to allow `^18.0.0`. This is tested for errors on this pr but is not actively tested and should be used with some caution.

### CODE REVIEW

**Comment by nickofthyme** [comment]
buildkite update vrt

**Comment by nickofthyme** [comment]
buildkite update vrt

**Comment by nickofthyme** [comment]
buildkite update vrt

**Review by markov00 — APPROVED** [review]
LGTM

**Pull request merged**
