### PR TITLE
build(deps): update dev dependencies

### PR DESCRIPTION
**Pull request by markov00**
## Summary

Updating a bunch of dev-dependencies to fix various security issues

### Checklist

Delete any items that are not applicable to this PR.

- [ ] Any consumer-facing exports were added to `src/index.ts` (and stories only import from `../src` except for test data & storybook)
- [ ] This was checked for cross-browser compatibility
- [ ] Proper documentation or storybook story was added for features that require explanation or tutorials
- [ ] Unit tests were updated or added to match the most common scenarios

### CODE REVIEW

**Review by nickofthyme — APPROVED** [review]

**Comment by markov00** [comment]
jenkins retest this please ❤️

**Comment by nickofthyme** [comment]
Really! The diff on this is one px ☝️ 

image

🧐🧐🧐
image

**Comment by nickofthyme** [comment]
jenkins retest this please

**Comment by nickofthyme** [comment]
Will be fixed by https://github.com/elastic/elastic-charts/pull/1130

**Pull request merged**
