### PR TITLE
feat(theme): move annotation default styles to `Theme`

### PR DESCRIPTION
**Pull request by nickofthyme**
## Summary

As part of the work to reclaim the charts theme from eui we need to adopt the line annotation styles defined [here](https://github.com/elastic/eui/blob/75d5b5afe7179dbc2764dd48078a8712b356366c/src/themes/charts/themes.ts#L27-L33). These styles are dependent on the theme type so to adopt this in `@elastic/charts` we added `lineAnnotation` & `rectAnnotation` to the `Theme`.

The new defaults are used from the theme and ignore `DEFAULT_ANNOTATION_LINE_STYLE` and `DEFAULT_ANNOTATION_RECT_STYLE`. To use these old default please use the desired legacy theme export.

## Details

image

- moves default styles to theme under `lineAnnotation` & `rectAnnotation`
- deprecated standalone default style exports (i.e. `DEFAULT_ANNOTATION_LINE_STYLE` and `DEFAULT_ANNOTATION_RECT_STYLE`)
- updates default annotation colors per theme

## Issues

related to #2069 

### Checklist

- [x] The proper **chart type** label has been added (e.g. `:xy`, `:partition`)
- [x] The proper **feature** labels have been added (e.g. `:interactions`, `:axis`)
- [x] All related issues have been linked (i.e. `closes #123`, `fixes #123`)
- [x] New public API exports have been added to `packages/charts/src/index.ts`
- [x] Unit tests have been added or updated to match the most common scenarios
- [x] The proper documentation and/or storybook story has been added or updated
- [x] Visual changes have been tested with `light` and `dark` themes

### CODE REVIEW

**Comment by nickofthyme** [comment]
buildkite update screenshots

**Review by markov00 — APPROVED** [review]
Everything looks fine to me! Thanks

**Comment by nickofthyme** [comment]
@gvnmagni are you okay with using the eui `darkShade` as the default color for line and rect annotations?

**Comment by nickofthyme** [comment]
buildkite update screenshots

**Pull request merged**
