### PR TITLE
docs: add CPU profile example

### PR DESCRIPTION
**Pull request by dgieselaar**
## Summary

Adds a storybook example with real-world APM profiling data.

### Checklist

Delete any items that are not applicable to this PR.

- [ ] Any consumer-facing exports were added to `src/index.ts` (and stories only import from `../src` except for test data & storybook)
- [ ] This was checked for cross-browser compatibility
- [ ] Proper documentation or storybook story was added for features that require explanation or tutorials
- [ ] Unit tests were updated or added to match the most common scenarios

### CODE REVIEW

**Review by markov00 — COMMENTED** [review]
TIL resolveJsonModule!
Thank you, it look all good to me.
One suggestion: what if we merge this after https://github.com/elastic/elastic-charts/pull/1033 and we include a Storybook `knob` to control the clip option?
You also need to update the Visual regression tests with that new story. If you want I can take from there and add both knobs and the VRT screenshot

**Comment by dgieselaar** [comment]
@markov00 sounds good to me wrt merging after #1033. And if you can update the tests that'd be very much appreciated!

**Review by markov00 — APPROVED** [review]
LGTM

**Review by monfera — APPROVED** [review]
Looks great, thanks Dario 🎉

**Pull request merged**
